apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    demo: filebeat
data:
  filebeat.yaml: |
    filebeat:
      config:
        mondules:
          path: /usr/share/filebeat/modules.d/*.yaml
          reload:
            enable: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    demo: emptydir
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: emptydir
  template:
    metadata:
      labels:
        app: nginx
        demo: emptydir
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.17.3
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yaml
          subPath: filebeat.yaml

      volumes:
      - name: nginx-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
          items:
            - key: filebeat.yaml
              path: filebeat.yaml