apiVersion: v1
kind: Pod
metadata:
  name: clusterip-demo-pod
  labels:
    app: nginx
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP #It is a default service, no need to mention here
  selector:
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80  #Service port
    targetPort: 80  #Container port
