apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer-pod
  labels:
    app: nginx
    demo: service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80