apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: # EFS volume Id

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  storageClassName: ""
  volumeName: efs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    demo: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-static-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: efs-static
spec:
  type: LoadBalancer
  selector:
    demo: efs-static
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
