apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: # EFS Filesystem Id
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/roboshop"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    demo: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-dynamic

---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
spec:
  type: LoadBalance
  selector:
    demo: efs-dynamic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    