apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: username
        valueFrom:
          configMapKeyRef:
            key: username
      - name: password
        valueFrom:
          configMapKeyRef:
            key: password
      